// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_ERM.src.Erm.DataAccess;

#nullable disable

namespace Erm.Migrations
{
    [DbContext(typeof(ErmDbContext))]
    [Migration("20240426064539_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Erm.src.Erm.DataAccess.BusinessProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Domain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("BusinessProcess", (string)null);
                });

            modelBuilder.Entity("Erm.src.Erm.DataAccess.RiskProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessProcessId")
                        .HasColumnType("int")
                        .HasColumnName("BusinessProcessId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Description");

                    b.Property<int>("OccurrenceProbability")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OccurrenceProbability");

                    b.Property<int>("PotentialBusinessImpact")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PotentialBusinessImpact");

                    b.Property<string>("RiskName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("RiskName");

                    b.HasKey("Id");

                    b.HasIndex("BusinessProcessId");

                    b.ToTable("RiskProfiles", (string)null);
                });

            modelBuilder.Entity("Erm.src.Erm.DataAccess.RiskProfile", b =>
                {
                    b.HasOne("Erm.src.Erm.DataAccess.BusinessProcess", "BusinessProcess")
                        .WithMany("RiskProfiles")
                        .HasForeignKey("BusinessProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessProcess");
                });

            modelBuilder.Entity("Erm.src.Erm.DataAccess.BusinessProcess", b =>
                {
                    b.Navigation("RiskProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
